# Generated by Django 5.0 on 2024-01-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_burger', models.IntegerField()),
                ('cantidad_bebida', models.IntegerField()),
                ('nombre_burger', models.CharField(max_length=40)),
                ('nombre_bebida', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio_combo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('recomendacion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('resena', models.CharField(max_length=500)),
            ],
        ),
    ]
